### ISSUE TITLE
진행관련 문의

### ISSUE THREAD

**Issue by xi-jjun** [choorai/retrospect-backend#10]
## 개요
@seokhwan-an @JoungMinJu 
jira 로 전반적인 프로젝트를 관리하는 것으로 이해했는데, issue를 쓰고 있는 것 같습니다.

혹시 issue를 사용하고계신 이유가 있는게 아니라면, jira에 티켓을 등록하셔서 진행해주세요. 아니면 지금이라도 jira가 아닌 GitHub에서 모든 것을 관리할거면 그렇게 하겠다는 결정을 해야할 것 같습니다. 프로젝트 관리가 이원화 되는 것은 좋지 않아보여요.

jira board : https://choorai.atlassian.net/jira/software/projects/RH/boards/1

간단 사용법 (FE wiki) : https://github.com/choorai/retrospect-frontend/wiki/Git-flow-IntelliJ-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0#2-git-flow-%EC%82%AC%EC%9A%A9%EB%B2%95

**Comment by seokhwan-an** [comment]
아 사실 대시보드를 만드는 법을 잘 몰라서 그전까지만 issue를 통해서 할려고 했는데 대시보드는 구축해주셨군요 감사합니다! 이제부터 jira로 하겠습니다!

**Comment by JoungMinJu** [comment]
감사합니다 !! jira로 넘어가도록 하겠습니다 :):)

**Comment by JoungMinJu** [comment]
감사합니다 !! jira로 넘어가도록 하겠습니다 :):)
